version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./bezkoder-app
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false","spring.datasource.username" : "$MYSQLDB_USER","spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD","spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect","spring.jpa.hibernate.ddl-auto" : "update"}'
    entrypoint: ["java", "-javaagent:/agent/inspectit-ocelot-agent.jar", "-Dinspectit.service-name=tutorial-service", "-Dinspectit.exporters.tracing.service-name=tutorial-service", "-Dinspectit.exporters.tracing.jaeger.enabled=ENABLED", "-Dinspectit.exporters.tracing.jaeger.protocol=http/thrift", "-Dinspectit.exporters.tracing.jaeger.endpoint=http://172.17.0.1:14268/api/traces", "-Dinspectit.exporters.metrics.influx.enabled=ENABLED", "-Dinspectit.exporters.metrics.influx.endpoint=http://172.17.0.1:8086", "-jar", "/bezkoder-app/app.jar"]
    deploy:
    volumes:
      - .m2:/root/.m2
      - ./agent:/agent
    stdin_open: true
    tty: true

volumes:
  db:
